LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Enabled: true

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 100

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# disable get/set warnings - many of our methods are performing API calls and get_ seems appropriate naming
Style/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Max: 200
